### ISSUE TITLE
I want to send with topic.

### ISSUE THREAD

**Issue by yukitoto** [yuki24/andpush#1]
Thank you for nice library. 
By using fcm, we can send push notification with device id and topic.

**Comment by yuki24** [comment]
I'm not familiar with Topic Messaging, but according to [the official documentation](https://firebase.google.com/docs/cloud-messaging/android/topic-messaging#topic-http-post-request) you can just set the `to` JSON key to something like `/topics/your-topic-name`.

```ruby
payload = {
  to: "/topics/foo-bar",
  data: {
    message: "This is a Firebase Cloud Messaging Topic Message!",
   }
}

response = client.push(payload)
```

**Comment by yuki24** [comment]
I just updated the README for clarity: [Topic Messaging](https://github.com/yuki24/andpush#topic-messaging). closing this issue since I believe sending to a topic has been possible since day one. It was just not documented well. Thanks!
