### ISSUE TITLE
NoMethodError (undefined method `new' for Andpush:Module):

### ISSUE THREAD

**Issue by YusukeHidaka** [yuki24/andpush#2]
NoMethodError (undefined method `new' for Andpush:Module):

newメソッドを使おうとすると存在しないと言われます。
なぜでしょうか？

[translation added by repo maintainer]
The `Andpush#new` initializer does not seem to exist. Any idea why this is happening?

**Comment by yuki24** [comment]
Waht version of the gem are you using? It's only available in version `0.2.0`.

```
bundle show andpush
```

**Comment by yuki24** [comment]
I believe this was caused by an older version of the gem. I'm closing this issue. Let me know if this is still an issue.
