### ISSUE TITLE
How can I close the client connection ?

### ISSUE THREAD

**Issue by sapnaSpaceo** [yuki24/andpush#3]
Hello,
client  = Andpush.new(server_key, pool_size: 25)
after creating the client Is there anyway to close the connection ?

**Comment by yuki24** [comment]
The andpush gem uses [the `net-http-persistent` gem](https://github.com/drbrain/net-http-persistent) under the hood. The connection object is also exposed as a public API, so you should be able to close the connection by calling the `#shutdown` method on the connection:

```ruby
require 'andpush'

client = Andpush.new("server-key", pool_size: 25)
client.request_handler.connection.shutdown
```
