### ISSUE TITLE
IOS Apn compatibility

### ISSUE THREAD

**Issue by lhrolim** [yuki24/andpush#5]
Hi, this is actually a question.

Can one use your gem to send also IOS push notifications through Firebase assuming the APN is correctly connected through the firebase panel?

Thanks

**Comment by yuki24** [comment]
Absolutely. In order to send a notification through APN using FCM just [specify a topic name as described in thier doc](https://firebase.google.com/docs/cloud-messaging/ios/send-multiple):

```
client  = Andpush.new(server_key, pool_size: 25)
payload = {
  to: /topics/foo-bar",
  priority: "high",
  notification: {
    body: "This is a Firebase Cloud Messaging Topic Message to APN!",
    title: "FCM Message",
  }
}

client.push(payload)
```

**Comment by yuki24** [comment]
I'm closing this issue, but happy to answer questions if you need help. Thanks!
