### ISSUE TITLE
Use FCM HTTP v1 API

### ISSUE THREAD

**Issue by kaito0228** [yuki24/andpush#9]
I want to use FCM HTTP v1 API via this gem.
Is this gem compatible with it?
If it supports, please tell me the implementation method.

↓legacy to HTTP v1 migrate doc
https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by yuki24** [comment]
Right now it's not compatible with the new v1 API. I haven't had time to look into this since the way v1 authenticates the request is fundamentally different. I'd like to add support for it, but sorry, it's probably not going to happen soon.

**Comment by kaito0228** [comment]
Thank you for the reaction!
I see.
I explore another way.
Since it is a good gem, I expect updates. (I would like to contribute if a good way is found.)
